name: PR Tests

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Tests
      uses: ./.github/actions/run-unit-tests
      with:
        python-version: "3.12"
        os: "ubuntu-latest"
        is_pr: "true"

  postgres-tests:
    name: PostgreSQL Integration Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: acapy_test
          POSTGRES_PASSWORD: acapy_test_pass
          POSTGRES_DB: acapy_test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - name: checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: PostgreSQL Integration Tests
      uses: ./.github/actions/run-postgres-tests
      with:
        python-version: "3.12"
        os: "ubuntu-latest"
